### ISSUE TITLE
Remove redundancies in tables needed for reference cases

### ISSUE THREAD

**Issue by cbolisetti** [accert-dev/ACCERT#22]
**Is your feature request related to a problem? Please describe.**
Currently, there is plenty of redundancy in the amount of information in the reference case tables. 

**Describe the solution you'd like**
We can remove some of the columns/tables by adding simple methods. A list of subtasks needed for this is below. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Subtasks**

- [ ] Remove columns in accounts like level, sub accounts, etc. We need to write methods that input the account number and output level, sub account, super account, etc. We can just do this for GNCOA since there is a consistent logic (EEDB has several exceptions). 
- [ ] Remove the need for the variable links table
- [ ] Streamline algorithms: 

-------
For Issue Closure
-------

- [ ] 1. Is the task fulfilled?
- [ ] 2. If not, does it contain explanation?
- [ ] 3. If closed without a pull request, has an explanation been provided?
